export const ruralEqEndpoints = {
  tillage: "gruntoobrobna-tekhnika",
  reapers: "zhatki",
  otherRural: "insha-silgosptekhnika",
  potato: "kartopliana-tekhnika",
  combine: "kombaini",
  logging: "lisozagotivelna-tekhnika",
  accessories: "obladnannia",
  postHarvest: "pisliazbiralna-tekhnika",
  sowingPlanting: "posivna-ta-sadilna-tekhnika",
  ruralRealEstate: "silskogospodarska-nerukhomist",
  fertilizerEq: "tekhnika-dlya-zagotivli-sina",
  harvestHayEq: "tekhnika-dlya-transportuvannia",
  wateringIrrigationEq: "tekhnika-dlya-polivu-ta-zroshennia",
  gardenEq: "tekhnika-dlya-tvarinnitstva",
  animalEq: "obladnannia-dlya-komunalnoyi-tekhniki",
  transportingEq: "tekhnika-dlya-sadu-ta-gorodu",
  tractors: "traktori",
};
